version: '2'

services:
  db:
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: secret_password
    restart: unless-stopped
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    restart: unless-stopped
    image: redis:3.0
    expose:
      - "6379"
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://database_user:secret_password@db/database_name
      REDIS_URL: redis://redis
      PORT: 8000
      DEBUG: "true"
    build: 
      context: ./backoffice
      dockerfile: Dockerfile.dev
    restart: unless-stopped 
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"
    volumes:
      - ./backoffice:/code
    depends_on:
      - db
      - redis
